npmRegistries:
  //npm.fontawesome.com:
    npmAlwaysAuth: true
    npmAuthToken: "6C7ACFC8-761F-4546-81E4-2E7BCB7503F5"

npmScopes:
  fortawesome:
    npmRegistryServer: https://npm.fontawesome.com/
